apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: my-app-namespace
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: backend-svc-http
  type: ClusterIP